Repository mapillary/mapillary-python-sdk, pull requests merged in 2021-08, with the labels that each got.

#83 [Requirement] Get All Detections for Image Key / Map Feature Key
  mapillary/__init__.py
  mapillary/config/api/__init__.py
  mapillary/controller/__init__.py
  mapillary/controller/detection.py
  mapillary/controller/feature.py
  mapillary/controller/image.py
  mapillary/controller/rules/.gitkeep
  mapillary/controller/rules/__init__.py
  mapillary/mapillary.py
  mapillary/models/api/entities.py
  mapillary/utils/filter.py
  mapillary/utils/format.py
  mapillary/utils/verify.py
  test.env
Labels: CLA Signed, enhancement, requirements, triage

#82 [Requirement] Get Image Looking At Requirement 3
  Pipfile
  Pipfile.lock
  mapillary/controller/image.py
  mapillary/mapillary.py
  mapillary/utils/filter.py
Labels: enhancement, CLA Signed, requirements, triage

#84 [Tests] Added method to easily pull in data, #72
  .gitignore
  tests/helper/client.py
  tests/helper/data/.gitkeep
  tests/helper/fetch.py
Labels: enhancement, CLA Signed, testing

#90 [Requirement] Get an image or a map feature given a valid ID
  mapillary/config/api/entities.py
  mapillary/controller/feature.py
  mapillary/controller/image.py
  mapillary/mapillary.py
  mapillary/models/api/entities.py
  mapillary/utils/format.py
  mapillary/utils/verify.py
Labels: enhancement, CLA Signed, feature, triage

#96 Updated `entities.py` to reflect API changes
  mapillary/config/api/entities.py
Labels: documentation, CLA Signed, api

#97 [Hotfix] Slight Refactoring
  mapillary/controller/detection.py
  mapillary/controller/image.py
  mapillary/mapillary.py
  mapillary/utils/filter.py
  mapillary/utils/verify.py
Labels: bug, documentation, CLA Signed, fix

#98 Revert "[Hotfix] Slight Refactoring"
  mapillary/controller/detection.py
  mapillary/controller/image.py
  mapillary/mapillary.py
  mapillary/utils/filter.py
  mapillary/utils/verify.py
Labels: CLA Signed

#94 [Requirements] 9. Get Features In shape/GeoJSON
  Pipfile
  Pipfile.lock
  mapillary/controller/detection.py
  mapillary/controller/feature.py
  mapillary/controller/image.py
  mapillary/mapillary.py
  mapillary/models/api/vector_tiles.py
  mapillary/models/geojson.py
  mapillary/utils/filter.py
  mapillary/utils/format.py
  mapillary/utils/verify.py
Labels: documentation, enhancement, CLA Signed, requirements

#99 Restore hotfixes1
  mapillary/controller/detection.py
  mapillary/controller/image.py
  mapillary/mapillary.py
  mapillary/utils/filter.py
  mapillary/utils/verify.py
Labels: CLA Signed

#95 [Requirements] 12. Save GeoJSON data locally
  Pipfile
  Pipfile.lock
  mapillary/controller/save.py
  mapillary/mapillary.py
  mapillary/utils/format.py
  mapillary/utils/verify.py
Labels: enhancement, CLA Signed, feature, requirements

#100 [Requirements] Requirement#10, Map Features From GeoJSON/Shape
  mapillary/controller/image.py
  mapillary/mapillary.py
  mapillary/models/api/vector_tiles.py
Labels: enhancement, CLA Signed, feature, requirements

#108 [Utils] Added decoding for image pixel geometry
  mapillary/utils/format.py
Labels: enhancement, CLA Signed, utility

#110 [Release] Package Release Changes
  MANIFEST.in
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  mapillary.toml
  mapillary/__init__.py
  mapillary/__version__.py
  mapillary/config/__init__.py
  mapillary/config/api/__init__.py
  mapillary/controller/__init__.py
  mapillary/utils/__init__.py
  setup.py
  src/mapillary/__init__.py
  src/mapillary/config/.gitkeep
  src/mapillary/config/__init__.py
  src/mapillary/config/api/__init__.py
  src/mapillary/config/api/entities.py
  src/mapillary/config/api/general.py
  src/mapillary/config/api/vector_tiles.py
  src/mapillary/controller/__init__.py
  src/mapillary/controller/detection.py
  src/mapillary/controller/feature.py
  src/mapillary/controller/image.py
  src/mapillary/controller/save.py
  src/mapillary/interface.py
  src/mapillary/models/.gitkeep
  src/mapillary/models/__init__.py
  src/mapillary/models/api/__init__.py
  src/mapillary/models/api/entities.py
  src/mapillary/models/api/vector_tiles.py
  src/mapillary/models/auth.py
  src/mapillary/models/client.py
  src/mapillary/models/exceptions.py
  src/mapillary/models/geojson.py
  src/mapillary/utils/.gitkeep
  src/mapillary/utils/__init__.py
  src/mapillary/utils/extract.py
  src/mapillary/utils/filter.py
  src/mapillary/utils/format.py
  src/mapillary/utils/time.py
  src/mapillary/utils/verify.py
Labels: enhancement, CLA Signed, github, requirements, refactor, pypi

#113 [Release] Updated `setup.py` for PyPi meta data
  setup.py
Labels: CLA Signed, pypi

#115 [Release] `mapillary` Windows installation/release fix
  Pipfile
  Pipfile.lock
  setup.py
Labels: CLA Signed, github, pypi

#112 [Testing] Hotfix For Tests
  Makefile
  Pipfile.lock
  pytest.ini
  tests/__init__.py
  tests/conftest.py
  tests/helper/client.py
  tests/utils/__init__.py
  tests/utils/test_extract.py
  tests/utils/test_filter.py
Labels: CLA Signed, testing

#118 [Documentation] `docs/` W/ `sphinx` Finalization, PyCharm Refactoring
  .gitignore
  Makefile
  Pipfile
  Pipfile.lock
  src/mapillary/__init__.py
  src/mapillary/config/__init__.py
  src/mapillary/config/api/__init__.py
  src/mapillary/config/api/entities.py
  src/mapillary/config/api/general.py
  src/mapillary/config/api/vector_tiles.py
  src/mapillary/controller/__init__.py
  src/mapillary/controller/detection.py
  src/mapillary/controller/feature.py
  src/mapillary/controller/image.py
  src/mapillary/controller/save.py
  src/mapillary/interface.py
  src/mapillary/models/__init__.py
  src/mapillary/models/api/__init__.py
  src/mapillary/models/api/entities.py
  src/mapillary/models/api/vector_tiles.py
  src/mapillary/models/auth.py
  src/mapillary/models/client.py
  src/mapillary/models/exceptions.py
  src/mapillary/models/geojson.py
  src/mapillary/utils/__init__.py
  src/mapillary/utils/extract.py
  src/mapillary/utils/filter.py
  src/mapillary/utils/format.py
  src/mapillary/utils/time.py
  src/mapillary/utils/verify.py
Labels: documentation, enhancement, CLA Signed, refactor

#123 [Documentation] `Docusaurus` instantiation
  .gitignore
  Makefile
  docs/.eslintrc.js
  docs/.gitignore
  docs/.prettierignore
  docs/.prettierrc
  docs/.stylelintrc.js
  docs/README.md
  docs/babel.config.js
  docs/blog/2019-05-28-first-blog-post.md
  docs/blog/2019-05-29-long-blog-post.md
  docs/blog/2021-08-01-mdx-blog-post.mdx
  docs/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  docs/blog/2021-08-26-welcome/index.md
  docs/blog/authors.yml
  docs/docs/intro.md
  docs/docs/sdk/_category_.json
  docs/docs/sdk/index.md
  docs/docs/sdk/mapillary.config.api.md
  docs/docs/sdk/mapillary.config.md
  docs/docs/sdk/mapillary.controller.md
  docs/docs/sdk/mapillary.md
  docs/docs/sdk/mapillary.models.api.md
  docs/docs/sdk/mapillary.models.md
  docs/docs/sdk/mapillary.utils.md
  docs/docs/tutorial-basics/_category_.json
  docs/docs/tutorial-basics/congratulations.md
  docs/docs/tutorial-basics/create-a-blog-post.md
  docs/docs/tutorial-basics/create-a-document.md
  docs/docs/tutorial-basics/create-a-page.md
  docs/docs/tutorial-basics/deploy-your-site.md
  docs/docs/tutorial-basics/markdown-features.mdx
  docs/docs/tutorial-extras/_category_.json
  docs/docs/tutorial-extras/manage-docs-versions.md
  docs/docs/tutorial-extras/translate-your-site.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/markdown-page.md
  docs/src/pages/styles.module.css
  docs/static/.nojekyll
  docs/static/img/docusaurus.png
  docs/static/img/favicon.ico
  docs/static/img/logo.svg
  docs/static/img/oss_logo.png
  docs/static/img/tutorial/docsVersionDropdown.png
  docs/static/img/tutorial/localeDropdown.png
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
  docs/yarn.lock
  scripts/documentation.py
  setup.py
  src/mapillary/interface.py
  src/mapillary/utils/__init__.py
  src/mapillary/utils/auth.py
  src/mapillary/utils/filter.py
Labels: documentation, enhancement, CLA Signed
